version: '3'

services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:15.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: site
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
